body:
  name: 'base_link'
  link:
    width: 0.136
    length: 0.3618
    thickness: 0.052
    mesh_file : 'stl/the_walking_thread/frame.stl'
    # mesh_file: 'None'
  inertia:
    mass: 0.12138
    inertia: {ixx: 0.2, ixy: 0.2, ixz: 0.2, iyy: 0.2, iyz: 0.2, izz: 0.2}
    origin: [0 0 0]



servo:
  velocity: 0.003141593
  effort: 0.5295591




coxa:
  name: 'coxa'
  link:
    length: 0.036
    radius: 0.02
    mesh_file : 'stl/the_walking_thread/coxa.stl'
    # mesh_file: 'None'
  inertia:
    mass: 0.12138
    inertia: {ixx: 0.2, ixy: 0.2, ixz: 0.2, iyy: 0.2, iyz: 0.2, izz: 0.2}
    origin: [0 0 0]

  joint:
    limit:
      lower: -45
      upper: +45
    origin: [0 -0.01730 -0.036]



femur:
  name: 'femur'
  link:
    length: 0.055
    radius: 0.02
    mesh_file : 'stl/the_walking_thread/femur.stl'
    # mesh_file: 'None'
  inertia:
    mass: 0.12138
    inertia: {ixx: 0.2, ixy: 0.2, ixz: 0.2, iyy: 0.2, iyz: 0.2, izz: 0.2}
    origin: [0 0 0]

  joint:
    limit:
      lower: -45
      upper: +45

    origin: [0 0 -0.055]



tibia:
  name: 'tibia'
  link:
    length: 0.1633
    radius: 0.0065
    mesh_file : 'stl/the_walking_thread/tibia.stl'
    # mesh_file: 'None'
  inertia:
    mass: 0.12138
    inertia: {ixx: 0.2, ixy: 0.2, ixz: 0.2, iyy: 0.2, iyz: 0.2, izz: 0.2}
    origin: [0 0 0]

  joint:
    limit:
      lower: +0
      upper: +135

    origin: [0 0 0]
