body:
  name: 'base_link'
  link:
    width: 0.136
    length: 0.3618
    thickness: 0.052
    # mesh_file : 'obj/the_walking_thread/frame.obj'
    mesh_file: 'None'
    rpy: [0 0 0]
  inertial:
    mass: 0.12138
    inertia: {ixx: 0.2, ixy: 0.2, ixz: 0.2, iyy: 0.2, iyz: 0.2, izz: 0.2}
    origin: [0 0 0]



servo:
  velocity: 0.2
  effort: 0.2



coxa:
  name: 'coxa'
  link:
    length: 0.036
    radius: 0.016
    mesh_file : 'obj/the_walking_thread/coxa.obj'
    rpy: [0 0 0]
  inertial:
    mass: 0.12138
    inertia: {ixx: 0.2, ixy: 0.2, ixz: 0.2, iyy: 0.2, iyz: 0.2, izz: 0.2}
    origin: [0 0 0]

  joint:
    limit:
      lower: -45
      upper: +45
    origin: [0 0 0]



femur:
  name: 'femur'
  link:
    length: 0.055
    radius: 0.02
    mesh_file : 'obj/the_walking_thread/femur.obj'
    rpy: [0 0 0]
  inertial:
    mass: 0.02696
    inertia: {ixx: 0.2, ixy: 0.2, ixz: 0.2, iyy: 0.2, iyz: 0.2, izz: 0.2}
    origin: [0 0 0]

  joint:
    limit:
      lower: -45
      upper: +45
    origin: [0 0 -0.01]



tibia:
  name: 'tibia'
  link:
    length: 0.1633
    radius: 0.13
    mesh_file : 'obj/the_walking_thread/tibia.obj'
    rpy: [0 0 0]
  inertial:
    mass: 0.08473
    inertia: {ixx: 0.2, ixy: 0.2, ixz: 0.2, iyy: 0.2, iyz: 0.2, izz: 0.2}
    origin: [0 0 0]

  joint:
    limit:
      lower: -135
      upper: +0
    origin: [0 0 -0.2]
