robot:
  name: 'the_wlaking_thread'

package:
  name: 'the_walking_thread_gazebo'
  meshes_path: 'src/urdf'

body:
  name: 'base_link'
  link:
    width: 0.117
    length: 0.3618
    thickness: 0.0525
    mesh_file : 'meshes/the_walking_thread/frame.stl'
  inertia:
    mass: 0.209677
    inertia: {ixx: 0.00022432, ixy: 0.00, ixz: 0.00, iyy: 0.0041164, iyz: 0.00, izz: 0.00422412}
    origin: [0 0 0.0006312]



servo:
  velocity: 0.003141593
  effort: 0.5295591




coxa:
  name: 'coxa'
  link:
    length: 0.0365
    radius: 0.019
    mesh_file : 'meshes/the_walking_thread/coxa.stl'
    # mesh_file: 'None'
  inertia:
    mass: 0.12131
    inertia: {ixx: 0.00009165, ixy: 0.00000598, ixz: -0.0000018, iyy: 0.00003309, iyz: -0.00001473, izz: 0.00008256}
    origin: [-0.00018108 -0.01243788 0.00165404]

  joint:
    limit:
      lower: -45
      upper: +45
    origin: [0 -0.019 -0.0365]



femur:
  name: 'femur'
  link:
    length: 0.057
    radius: 0.03
    mesh_file : 'meshes/the_walking_thread/femur.stl'
  inertia:
    mass: 0.02748837
    inertia: {ixx: 0.00001094, ixy: 0.00, ixz: 0.00, iyy: 0.00001457, iyz: 0.00, izz: 0.00002278}
    origin: [0.00165535 -0.02849892 0.00]

  joint:
    limit:
      lower: -45
      upper: +45

    origin: [0 0 -0.057]



tibia:
  name: 'tibia'
  link:
    length: 0.163
    radius: 0.0065
    mesh_file : 'meshes/the_walking_thread/tibia.stl'
  inertia:
    mass: 0.08475
    inertia: {ixx: 0.0001634, ixy: -0.00000317, ixz: -0.00000029, iyy: 1.251e-05, iyz: 0.00000318, izz: 0.00016808}
    origin: [-0.00173997 -0.03291755 0.00160352]

  joint:
    limit:
      lower: +0
      upper: +135

    origin: [0 0 0]
