heaxapod:
  # PUBLISH ALL STATE JOINTS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 30


  # LEFT FRONT LEG
  left_front_base_link_to_coxa_transmition:
    type: effort_controllers/JointPositionController
    joint: left_front_base_link_to_coxa_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_front_coxa_to_femur_transmition:
    type: effort_controllers/JointPositionController
    joint: left_front_coxa_to_femur_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_front_femur_to_tibia_transmition:
    type: effort_controllers/JointPositionController
    joint: left_front_femur_to_tibia_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}



  # LEFT CENTRAL LEG
  left_central_base_link_to_coxa_transmition:
    type: effort_controllers/JointPositionController
    joint: left_central_base_link_to_coxa_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_central_coxa_to_femur_transmition:
    type: effort_controllers/JointPositionController
    joint: left_central_coxa_to_femur_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_central_femur_to_tibia_transmition:
    type: effort_controllers/JointPositionController
    joint: left_central_femur_to_tibia_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}



  # LEFT REAR LEG
  left_rear_base_link_to_coxa_transmition:
    type: effort_controllers/JointPositionController
    joint: left_rear_base_link_to_coxa_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_rear_coxa_to_femur_transmition:
    type: effort_controllers/JointPositionController
    joint: left_rear_coxa_to_femur_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_rear_femur_to_tibia_transmition:
    type: effort_controllers/JointPositionController
    joint: left_rear_femur_to_tibia_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}




  # RIGHT FRONT LEG
  right_front_base_link_to_coxa_transmition:
    type: effort_controllers/JointPositionController
    joint: right_front_base_link_to_coxa_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_front_coxa_to_femur_transmition:
    type: effort_controllers/JointPositionController
    joint: right_front_coxa_to_femur_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_front_femur_to_tibia_transmition:
    type: effort_controllers/JointPositionController
    joint: right_front_femur_to_tibia_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}



  # RIGHT CENTRAL LEG
  right_central_base_link_to_coxa_transmition:
    type: effort_controllers/JointPositionController
    joint: right_central_base_link_to_coxa_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_central_coxa_to_femur_transmition:
    type: effort_controllers/JointPositionController
    joint: right_central_coxa_to_femur_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_central_femur_to_tibia_transmition:
    type: effort_controllers/JointPositionController
    joint: right_central_femur_to_tibia_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}



  # RIGHT REAR LEG
  right_rear_base_link_to_coxa_transmition:
    type: effort_controllers/JointPositionController
    joint: right_rear_base_link_to_coxa_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_rear_coxa_to_femur_transmition:
    type: effort_controllers/JointPositionController
    joint: right_rear_coxa_to_femur_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_rear_femur_to_tibia_transmition:
    type: effort_controllers/JointPositionController
    joint: right_rear_femur_to_tibia_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
